name: fast-ci

on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
     branches:
        - 'main'

jobs:   
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm run ci
      - run: npm run lint || true




  docker:
    name: Docker build and publish
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name:  Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metada (tags and labels) for Docker
        id: tag
        uses: docker/metadata-action@v5
        with:
          images: wallacestm/fast-todo
          tags: |
            # Se o trigger foi uma tag (ex: v1.0.0), a imagem Docker terá a tag 'v1.0.0'
            type=ref,event=tag
            # Se o trigger foi um push na branch 'main', a imagem terá duas tags: 'latest' e o hash do commit (ex: f1a2b3c)
            type=raw,value=latest,enable={{is_default_branch}}
            # Se o trigger foi um pull request, a imagem terá a tag 'PR-numero-do-pr'
            type=ref,event=pr,prefix=PR-
            type=sha
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with: 
          push: true
          tags: ${{ steps.tag.outputs.tags }}
          labels: ${{ steps.tag.outputs.labels }}